const PhongFS =
    [
        '#version 300 es',
        '#ifdef GL_ES',
        'precision highp float;',
        '#endif',
        'uniform sampler2D uSampler0;',
        'uniform sampler2D uSampler1;',
        'in highp vec3 vLightDir;',
        'in vec3 vNormal;',
        'in vec4 vColor;',
        'in vec3 vPosition;',
        'in vec2 vTextureCoords;',
        'uniform vec3 uLightPosition;',
        'uniform float uc1;',
        'uniform float uc2;',
        'uniform float uAmbientIntensity;',
        'uniform vec3 uAmbientLightColor;',
        'uniform vec3 uDiffuseLightColor;',
        'uniform vec3 uSpecularLightColor;',
        'uniform float uPropMat;',
        'uniform float uPropDig;',
        'uniform float uShadingModel;',
        'uniform float uAmbientCoeff;',
        'const float shininess = 5.0;',
        'out vec4 fragColor;',
        'void main(void) {',
        'vec4  digTex= texture(uSampler0, vTextureCoords);',
        'vec4  matTex= texture(uSampler1, vTextureCoords);',
        'matTex.a *= uPropMat;',
        'digTex.a *= uPropDig;',
            ' vec3 normal = 0.5*normalize(texture(uSampler1, vTextureCoords).rgb* 1.0 - 0.5);',
        'vec3 lightDirection = normalize(uLightPosition - vPosition);',
        'float d = distance(uLightPosition,vPosition);',

            'float diffuseLightDotM = max(dot(vNormal+normal, lightDirection), 0.0);',
            'vec3 reflectionVectorM = normalize(reflect(-lightDirection, vNormal+normal));',
        'vec3 viewVectorEye = -normalize(vPosition);',
        'float specularLightDotM = max(dot(reflectionVectorM, viewVectorEye), 0.0);',
        'float specularLightParamM = pow(specularLightDotM, shininess);',
        'float attenuation = 1.0 / (1.0 + uc1 * d + uc2 * d * d);',
        'vec3 vLightWeighting = uAmbientLightColor * uAmbientIntensity + (uDiffuseLightColor * diffuseLightDotM + uSpecularLightColor * specularLightParamM) * attenuation;;' ,
            'fragColor = (digTex ) * vec4(vLightWeighting, 1);',
        '',
        '',
        '}',
    ].join('\n');
export default PhongFS;